### ISSUE TITLE
Local imports

### ISSUE THREAD

**Issue by mereolog** [Cognonto/kko#6]
You have an imports to a local file:

```
<http://kbpedia.org/kbpedia/rc#> a owl:Ontology ;
	owl:versionIRI :v250 ;
	owl:imports <https://www.w3.org/2009/08/skos-reference/skos-owl1-dl.rdf> , <file:///kbpedia/2.50/owl/kko.n3> ;
	dc:date "2020-02-24T20:00:00Z"@en ;
```

**Comment by mkbergman** [comment]
Yes, as instructions elsewhere indicate, you need to separately download this file and install it locally. We will look to provide an alternate solution going forward.
